### ISSUE TITLE
Name for targets possible ?

### ISSUE THREAD

**Issue by NiTRoeSE** [mbelloiseau/website-monitoring#4]
Hi, first thanks for your great work, it safed me a lot of time. 

I just have the question if its possible to change the displaying of targets ( urls ) in "website-monitoring" dashboard dropdown list to a name instead of the blank url ?

In the "overview-dashboard" its possible to add overwrites and replace in this way urls with names in the table.
In  the "website-monitoring" dashboard is a target variable used to select the targets. As far as i know its just the "instance" which is by design the target url.

Is there any way to modify the config that prometheus stores also a name to a target so its possible to select targets over name in the "website-monitoring" dashboard?

Thanks in advanced.

**Comment by mbelloiseau** [comment]
> I just have the question if its possible to change the displaying of targets ( urls ) in "website-monitoring" dashboard dropdown list to a name instead of the blank url ?

Hi, I'm not sure to understand when you say "blank url", could you provide a screenshot ?
