### ISSUE TITLE
docker compose errors

### ISSUE THREAD

**Issue by DJR-FP** [mbelloiseau/website-monitoring#8]
after cloning and running the docker compose up, I get the following error -

T19:33:18+0000 lvl=eror msg="Failed to read plugin provisioning files from directory" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins error="open /etc/grafana/provisioning/plugins: no such file or directory"
website-monitoring-grafana-1            | t=2023-02-13T19:33:18+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: no such file or directory"
website-monitoring-grafana-1            | t=2023-02-13

**Comment by mbelloiseau** [comment]
Hi,

To avoid this error message

```
     volumes:
     - "./config/grafana/provisioning:/etc/grafana/provisioning"
 ```

Should be something like

```
     volumes:
     - "./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources"
     - "./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
 ```
